events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;

    gzip  on;

    include /etc/nginx/conf.d/*.conf;

    ssl_certificate /home/dinis/projects/study/Clouds/lab1/ssl/localhost.crt;
    ssl_certificate_key /home/dinis/projects/study/Clouds/lab1/ssl/localhost.key;

    server {
        listen 80;
        listen [::]:80;
        server_name _;
        return 301 https://$host$request_uri;
    }
}
